# This case study consists of 1000 marks and the solution file is expected to be submitted in the upcoming session for evaluation.

In [20]:
import numpy as np
from numpy.random import randint as ri
from numpy.random import random as rand

### 1.Create two matrices of 3*3 and perform the arithmatic operations metioned in below "print" statements

In [22]:
mat1 = np.arange(1,10).reshape(3,3)
mat1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
mat2 = np.array(ri(1,9,9)).reshape(3,3)
mat2

array([[8, 6, 2],
       [1, 5, 1],
       [8, 3, 3]])

In [25]:
mat1 = np.arange(9).reshape(3,3)
mat2 = np.array(ri(0,9,9)).reshape(3,3)
mat1
mat2
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


print("\nAddition\n------------------\n", mat1+mat2)
print("\nMultiplication\n------------------\n",  mat1*mat2)


print("\nDivision\n------------------\n",  mat1/mat2)
print("\nLinear combination: 3*A - 2*B\n-----------------------------\n",  3*mat1-2*mat2)


print("\nAddition of a scalar (100)\n-------------------------\n", mat1+100)


print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3)
print("\nExponentiation, mat1 sq-root using pow function\n-------------------------------------------\n",mat1**0.5)


1st Matrix of random single-digit numbers
----------------------------------------
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[3 0 8]
 [6 8 7]
 [1 3 7]]

Addition
------------------
 [[ 3  1 10]
 [ 9 12 12]
 [ 7 10 15]]

Multiplication
------------------
 [[ 0  0 16]
 [18 32 35]
 [ 6 21 56]]

Division
------------------
 [[0.                inf 0.25      ]
 [0.5        0.5        0.71428571]
 [6.         2.33333333 1.14285714]]

Linear combination: 3*A - 2*B
-----------------------------
 [[ -6   3 -10]
 [ -3  -4   1]
 [ 16  15  10]]

Addition of a scalar (100)
-------------------------
 [[100 101 102]
 [103 104 105]
 [106 107 108]]

Exponentiation, matrix cubed here
----------------------------------------
 [[  0   1   8]
 [ 27  64 125]
 [216 343 512]]

Exponentiation, mat1 sq-root using pow function
-------------------------------------------
 [[0.         1.         1.41421356]
 [1.73205081 2.         2.2360679

C:\Users\JSM\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: RuntimeWarning: divide by zero encountered in true_divide
  del sys.path[0]


Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.

NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions”(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

### 2.Create two 3 * 3 matrices and perform the following operations as describe in print statement.

In [28]:
mat1 = np.arange(1,10).reshape(3,3)
mat1
mat2 = np.array(ri(1,9,9)).reshape(3,3)
mat2


array([[4, 8, 3],
       [7, 7, 1],
       [8, 6, 6]])

In [3]:
help(np)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [4]:
from numpy.random import randint as ri
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,9,9)).reshape(3,3)

print("\n1st Matrix of random single-digit numbers\n","-"*50,"\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n","-"*50,"\n",mat2)


print("\nSum of all numbers in 1st matrix\n","-"*50,"\n",np.sum(mat1))
print("\nSum of all numbers in columns of 1st matrix\n","-"*50,"\n",np.sum(mat1, axis=1))


print("\nSum of all numbers in rows of 1st matrix\n","-"*50,"\n",np.sum(mat1, axis=0))
print("\nProduct of all numbers in rows of 1st matrix\n","-"*50,"\n",np.prod(mat1, axis=0))


print("\nProduct of all numbers in columns of 2nd matrix\n","-"*50,"\n",np.prod(mat2, axis=1))
print("\nMean of all numbers in 1st matrix\n","-"*50,"\n",np.mean(mat1))


print("\nStandard deviation of all numbers in 1st matrix\n","-"*50,"\n",np.std(mat1))


mat1=np.array(ri(1,100,9)).reshape(3,3)
print("\nModified matrix of random numbers from 1 to 99\n","-"*50,"\n",mat1)


print("\nStandard deviation of all numbers in the modified matrix, a larger number\n","-"*80,"\n",np.std(mat1))


print("\nVariance of all numbers in the modified matrix, a larger number\n","-"*80,"\n",np.var(mat1))


print("\nMedian of all numbers in the modified matrix\n","-"*60,"\n",np.median(mat1))



1st Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[6 9 8]
 [1 9 3]
 [1 7 1]]

2nd Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[2 7 5]
 [3 5 7]
 [5 7 4]]

Sum of all numbers in 1st matrix
 -------------------------------------------------- 
 45

Sum of all numbers in columns of 1st matrix
 -------------------------------------------------- 
 [23 13  9]

Sum of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 [ 8 25 12]

Product of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 [  6 567  24]

Product of all numbers in columns of 2nd matrix
 -------------------------------------------------- 
 [ 70 105 140]

Mean of all numbers in 1st matrix
 -------------------------------------------------- 
 5.0

Standard deviation of all numbers in 1st matrix
 -------------------------------------------------- 
 3.2998316455372

###  3.Create a 3 \* 3 Matrix and Modify its shape to 9\*1 matrix.

In [7]:
##Solution
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat1

array([[1, 2, 5],
       [3, 2, 5],
       [4, 1, 5]])

In [8]:
maat1= np.sort(mat1.reshape(9,1))
maat1

array([[1],
       [2],
       [5],
       [3],
       [2],
       [5],
       [4],
       [1],
       [5]])

### 4.Sort

In [9]:
A = np.array(ri(1,100,10)) # Vector of random interegrs
print("\nVector of 10 random integers from 1 to 100\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))



Vector of 10 random integers from 1 to 100
 -------------------------------------------------- 
 [81 83 54 77 50 35 41 70 31 60]

Here is the sorted vector
 -------------------------------------------------- 
 [31 35 41 50 54 60 70 77 81 83]


In [3]:
M = np.random.randint(1,100,25).reshape(5,5) #  5*5 Matrix of random interegrs
print("\n5x5 Matrix of random integers\n",'-'*50,"\n",M)
print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M,axis=0)) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M,axis=1))


5x5 Matrix of random integers
 -------------------------------------------------- 
 [[92 13 71 86  1]
 [98 95 51 42 66]
 [30 82 13 31 48]
 [72 95 50 62 39]
 [42 83 94 54 31]]

Here is the sorted matrix along each row
 -------------------------------------------------- 
 [[30 13 13 31  1]
 [42 82 50 42 31]
 [72 83 51 54 39]
 [92 95 71 62 48]
 [98 95 94 86 66]]

Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[ 1 13 71 86 92]
 [42 51 66 95 98]
 [13 30 31 48 82]
 [39 50 62 72 95]
 [31 42 54 83 94]]


### 5.Create a,b,c  10 element vectors of random integers and perform the respective operation mentioned in print statement

In [13]:
# Fill the following ***** with appropriate solution.
a=np.array(ri(1,100,10))
b=np.array(ri(1,100,10))
c=np.array(ri(1,100,10))

print("a:", a)
print("b:", b)
print("c:", c)

print("Max of a:", np.max(a))
print("Max of b:",np.max(b))


print("Max of a location:", (np.argmax(a)))
print("Max of b location:", (np.argmax(b)))
print("Max of c location:", (np.argmax(c)))

#print("Max of a:", *****)
#print("Max of b:", ****)


#print("Max of a location:", ******)
#print("Max of b location:", ******)
#print("Max of c location:", ******)



a: [18 37 65 92 69 67 20  8 24 97]
b: [59  9 42 35 32 22 95 65 46 20]
c: [24 95 31 79 43 46 61 52 57 27]
Max of a: 97
Max of b: 95
Max of a location: 9
Max of b location: 6
Max of c location: 1


## Universal functions

6. Create 3*3 matrices of random single-digit numbers.<br/>
Apply universal functions on it. (square root,exponetial,log10,Modulo etc.)

In [17]:

mat1 = np.array(ri(1,10,9).reshape(3,3))
mat2 = np.array(ri(0,9,9).reshape(3,3))
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))


print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))


print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log(mat1))


print("\nModulo reminder using np\n",'-'*50,"\n", np.remainder(mat1,mat2))



1st Matrix of random single-digit numbers
----------------------------------------
 [[7 6 9]
 [6 8 6]
 [1 3 3]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[3 1 6]
 [4 6 1]
 [7 2 5]]

Sq-root of 1st matrix using np
------------------
 [[2.64575131 2.44948974 3.        ]
 [2.44948974 2.82842712 2.44948974]
 [1.         1.73205081 1.73205081]]

Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[1.09663316e+03 4.03428793e+02 8.10308393e+03]
 [4.03428793e+02 2.98095799e+03 4.03428793e+02]
 [2.71828183e+00 2.00855369e+01 2.00855369e+01]]

10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[1.94591015 1.79175947 2.19722458]
 [1.79175947 2.07944154 1.79175947]
 [0.         1.09861229 1.09861229]]

Modulo reminder using np
 -------------------------------------------------- 
 [[1 0 3]
 [2 2 0]
 [1 1 3]]


### 7.Generating matrices from distributions

In [43]:

print("Random number generation (from Uniform distribution)")
print(np.array(rand(6)).reshape(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3))

print("Random integer vector:",np.random.randint(1,100,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")
print(np.random.randint(1,100,10).reshape((5,2))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)

print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw

Random number generation (from Uniform distribution)
[[0.25730161 0.42961572 0.86955959]
 [0.25671217 0.72945205 0.74220015]]
Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[ 7.60409751e-04  9.11925807e-01 -6.66726278e-01]
 [-7.72438306e-01  1.17650306e+00  1.43047956e+00]
 [-1.04482045e+00 -2.13684724e-01 -1.51664435e-01]
 [-1.76190178e+00 -7.10119495e-01  2.24510404e+00]]
Random integer vector: [39 48 32 58 90 16 85 19 71 56]

Random integer matrix
[[22  6]
 [47  7]
 [51 36]
 [87 54]
 [12 62]]

20 samples drawn from a dice throw: [2 6 2 3 4 3 1 4 3 3 6 4 2 4 3 5 2 1 3 6]


### 8.Find the nearest value from a given number in an array using NumPy.

[5 8 7 1 7]


8

In [52]:
#Steps
#Create an array of 5 random element from 1 to 12
#Suppose find the nearest values of 10 in an array so set value=10
#find the index where difference is minimum and get the element
an=np.array(ri(1,12,5))
print(an)
an[an.argmax()]

[10  4 10  5  4]


10

### 9.Write code using numpy to produce following output
[[0 0 0] [0 1 2] [0 2 4]]

In [58]:
mat = np.array([[0, 0, 0], [0, 1, 2], [0, 2, 4]])
print(mat)

[[0 0 0]
 [0 1 2]
 [0 2 4]]
